common: &common
  machine: true
  working_directory: ~/build-tools

test_steps: &test_steps
  <<: *common
  steps:
    - checkout
    - run:
        name: set node keys
        command: |
          echo "node ${NODE_VERSION}"
          echo ${NODE_VERSION} > .node-version
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
    - restore_cache:
        key: yarn-cache-v2-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
    - restore_cache:
        key: dont-break-cache-{{ checksum ".node-version" }}-{{ checksum ".dont-break.json" }}
    - run:
        name: initial-steps
        command: |
          npm run install-ci-tools
          ci-tools-upgrade-node
          ci-tools-upgrade-yarn
    - run:
        name: pre-deps
        command: |
          sudo chmod -R a+w /usr/local
          yarn config set cache-folder ~/.cache/yarn
    - run:
        name: install-deps
        command: |
          yarn --frozen-lockfile --ignore-engines
          if [ "${NPM_TOKEN}" != "" ]; then
            ./scripts/install-dont-break.sh
            cp -f .circleci/.npmrc ~
            yarn global add --ignore-engines "@egis/egis-ui-test-utils@^3.0.0-pre.1"
            test-utils-update-chrome
          fi
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
        paths:
          - node_modules
          - yarn.lock
    - run:
        name: post-deps
        command: |
          mkdir ci-artifacts
          OUT_DIR=ci-artifacts yarn ci-tools-collect-deps-versions
          cp yarn.lock ci-artifacts/
        when: always
    - store_artifacts:
        path: ci-artifacts/
    - run:
        name: test
        command: |
          yarn test
          if [ "${NPM_TOKEN}" != "" ]; then
            cp -f .circleci/.npmrc ~
            dont-break --timeout 600
          fi
    - save_cache:
        key: yarn-cache-v2-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
        paths:
          - ~/.cache/yarn
    - save_cache:
        key: dont-break-cache-{{ checksum ".node-version" }}-{{ checksum ".dont-break.json" }}
        paths:
          - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-egis-ui
          - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-esign
          - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-portal-app
          - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-bulk-capture

version: 2
jobs:
  test8:
    environment:
      NODE_VERSION: 8.10.0
    <<: *test_steps
  test6:
    environment:
      NODE_VERSION: 6.0.0
    <<: *test_steps
  test10:
    environment:
      NODE_VERSION: 10.14.2
    <<: *test_steps
  test11:
    environment:
      NODE_VERSION: 11.4.0
    <<: *test_steps

  semantic-version:
    <<: *common
    environment:
      NODE_VERSION: 8.10.0
    steps:
      - checkout
      - run:
          name: set node keys
          command: echo ${NODE_VERSION} > .node-version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
      - run:
          name: set node version
          command: |
            npm run install-ci-tools
            ci-tools-upgrade-node
            ci-tools-upgrade-yarn
      - run:
          name: semantic-version
          command: yarn simple-semantic-release-pre

  publish:
    <<: *common
    environment:
      NODE_VERSION: 8.10.0
    steps:
      - checkout
      - run:
          name: set node keys
          command: echo ${NODE_VERSION} > .node-version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}-{{ checksum ".node-version" }}
      - run:
          name: set node version
          command: |
            npm run install-ci-tools
            ci-tools-upgrade-node
            ci-tools-upgrade-yarn
      - run:
          name: publish
          command: |
            OWNER=egis yarn simple-semantic-release
            yarn semantic-dependents-updates-github || true

workflows:
  version: 2
  main:
    jobs:
      - test6:
          context: org-global
      - test8:
          context: org-global
      - publish:
          filters:
            branches:
              only: master
          requires:
            - test6
            - test8
          context: org-global
      - semantic-version:
          requires:
            - test8
          context: org-global
