version: 2
jobs:
  build:
    machine: true
    working_directory: ~/build-tools
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: dont-break-cache
      - run:
          name: Install node@8.10.0
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v8.10.0
            nvm alias default v8.10.0

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: pre-deps
          command: |
            npm install -g yarn@1.5.1
            sudo chmod -R a+w /usr/local
            yarn config set cache-folder ~/.cache/yarn
            if [ "${NPM_TOKEN}" == "" ]; then rm .npmrc; fi
      - run:
          name: install-deps
          command: |
            npm run setup
            if [ "${NPM_TOKEN}" != "" ]; then
              ./scripts/install-dont-break.sh
              npm install -g .
              cp -f .npmrc ~
              yarn global add "@egis/egis-ui-test-utils@^2.27.2-pre.1"
              update-chrome
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yarn.lock
      - run:
          name: post-deps
          command: |
            mkdir ci-artifacts
            grep "version\"\:" node_modules/*/*/package.json > ci-artifacts/npm_versions.txt
            grep "version\"\:" node_modules/*/package.json >> ci-artifacts/npm_versions.txt
            grep "version\"\:" node_modules/*/*/*/package.json >> ci-artifacts/npm_versions.txt
            cp yarn.lock ci-artifacts/
          when: always
      - store_artifacts:
          path: ci-artifacts/
      - run:
          name: test
          environment:
            KEEP_MODIFIED_PACKAGE: true
          command: |
            npm test
            merge-build-tools-deps && git checkout -- package.json
            if [ "${NPM_TOKEN}" != "" ]; then
              dont-break --timeout 600
            fi
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dont-break-cache
          paths:
            - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-egis-ui
            - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-esign
            - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-portal-app
            - /tmp/egis-build-tools-v-0-0-0-semantic-release-against-egis-bulk-capture
      - run:
          name: deploy
          command: ./scripts/semantic-release.sh
