common: &common
  docker:
      - image: egis/papertrail-ci
  working_directory: /home/tester/build-tools

test_steps: &test_steps
  <<: *common
  steps:
    - checkout
    - run:
        name: build-cache-key
        command: |
          mkdir ci-artifacts
          cat package.json | jq '.dependencies, .devDependencies' > cache-key.txt
          echo "node ${NODE_VERSION}" >> cache-key.txt
          cp cache-key.txt ci-artifacts/
    - restore_cache:
        key: dependency-cache-{{ checksum "cache-key.txt" }}
    - restore_cache:
        key: yarn-cache-v2-{{ checksum "cache-key.txt" }}
    - restore_cache:
        key: dont-break-cache-v1-{{ checksum "cache-key.txt" }}-{{ checksum ".dont-break.json" }}
    - run:
        name: initial-steps
        command: |
          ci-tools-upgrade-node
          ci-tools-upgrade-yarn
          yarn global add yarn-retry
    - run:
        name: xvfb
        command: Xvfb :99 -screen 0 1280x1024x24
        background: true
    - run:
        name: install-deps
        command: |
          yarn-retry -- --frozen-lockfile --ignore-engines
          if [ "${NPM_TOKEN}" != "" ]; then
            ./scripts/install-dont-break.sh
          fi
    - save_cache:
        key: dependency-cache-{{ checksum "cache-key.txt" }}
        paths:
          - node_modules
    - run:
        name: post-deps
        command: |
          OUT_DIR=ci-artifacts yarn ci-tools-collect-deps-versions
        when: always
    - store_artifacts:
        path: ci-artifacts/
    - run:
        name: test
        command: |
          yarn test
          if [ "${NPM_TOKEN}" != "" ]; then
            cp -f .circleci/.npmrc ~
            dont-break --timeout 600
          fi
    - save_cache:
        key: yarn-cache-v2-{{ checksum "cache-key.txt" }}
        paths:
          - ~/.cache/yarn
    - save_cache:
        key: dont-break-cache-v1-{{ checksum "cache-key.txt" }}-{{ checksum ".dont-break.json" }}
        paths:
          - /tmp

version: 2
jobs:
  test8:
    environment:
      NODE_VERSION: 8.10.0
    <<: *test_steps
  test10:
    environment:
      NODE_VERSION: 10.14.2
    <<: *test_steps
  test11:
    environment:
      NODE_VERSION: 11.4.0
    <<: *test_steps

  publish-test:
    <<: *common
    environment:
      NODE_VERSION: 8.16.0
    steps:
      - checkout
      - run:
          name: build-cache-key
          command: |
            cat package.json | jq '.dependencies, .devDependencies' > cache-key.txt
            echo "node ${NODE_VERSION}" >> cache-key.txt
      - restore_cache:
          key: dependency-cache-{{ checksum "cache-key.txt" }}
      - run:
          name: semantic-version
          command: |
            if [ "${GH_TOKEN}" != "" ]; then
              ALLOW_FAILING=false yarn simple-semantic-release-pre
            fi

  publish:
    <<: *common
    environment:
      NODE_VERSION: 8.10.0
    steps:
      - checkout
      - run:
          name: build-cache-key
          command: |
            cat package.json | jq '.dependencies, .devDependencies' > cache-key.txt
            echo "node ${NODE_VERSION}" >> cache-key.txt
      - restore_cache:
          key: dependency-cache-{{ checksum "cache-key.txt" }}
      - run:
          name: publish
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" == "egis" ]; then
              yarn semantic-release && yarn semantic-dependents-updates-github
            fi

workflows:
  version: 2
  main:
    jobs:
      - test6:
          context: org-global
      - test8:
          context: org-global
      - publish-test:
          filters:
            branches:
              ignore: master
          requires:
            - test8
          context: org-global
      - publish:
          filters:
            branches:
              only: master
          requires:
            - test6
            - test8
          context: org-global
