version: 2
jobs:
  build:
    working_directory: ~/build-tools
    docker:
      - image: egis/build-slave
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: pre-deps
          command: |
            node --version
            npm --version
      - run:
          name: install-deps
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then rm .npmrc; fi
            yarn --ignore-engines
            if [ "${CIRCLE_BRANCH}" == "master" ]; then yarn global add dont-break@1.10.0; fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: post-deps
          command: |
            mkdir ci-artifacts
            grep "version\"\:" node_modules/*/*/package.json > ci-artifacts/npm_versions.txt
            grep "version\"\:" node_modules/*/package.json >> ci-artifacts/npm_versions.txt
            grep "version\"\:" node_modules/*/*/*/package.json >> ci-artifacts/npm_versions.txt
            cp yarn.lock ci-artifacts/
      - store_test_results:
          path: ci-artifacts/
      - run:
          name: test
          command: |
            npm test
            node merge-build-tools-deps.js && git checkout -- package.json
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cp -f .npmrc ~
              dont-break --timeout 600
            fi
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_USERNAME}" == "egis" ]; then
              npm run semantic-release || true
            fi
